# Generated by Django 3.2.5 on 2023-08-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vr_code',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='vr_code_status',
            field=models.IntegerField(default=0),
        ),
    ]
