# Generated by Django 3.2.5 on 2023-08-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230806_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
