# Generated by Django 3.2.5 on 2023-08-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230819_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category_id',
            new_name='category',
        ),
    ]
