# Generated by Django 3.2.5 on 2023-08-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_category_id_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='delivery_type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
