# Generated by Django 3.2.5 on 2023-08-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_menu_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='services',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
