# Generated by Django 3.2.5 on 2023-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230820_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='delfrom',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='code',
            name='delto',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='code',
            name='timefrom',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='code',
            name='timeto',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
