# Generated by Django 3.2.5 on 2023-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230820_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='service',
            field=models.CharField(default='Regular Timing', max_length=256),
        ),
    ]
