# Generated by Django 3.2.5 on 2023-08-26 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='amount',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='promocodes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_user', to='app.user'),
        ),
    ]
