# Generated by Django 3.2.5 on 2023-08-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20230826_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeawayclosetime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=256)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='meals',
            name='delivery_price',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='meal_text',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='qty',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals_category', to='app.category'),
        ),
    ]
