# Generated by Django 3.2.5 on 2023-09-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_timings_delivery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_data',
        ),
    ]
