# Generated by Django 3.2.5 on 2023-09-16 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_meals_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=256, null=True)),
                ('meal_type', models.CharField(max_length=256, null=True)),
                ('sub_status', models.CharField(max_length=256, null=True)),
                ('sub_order_ids', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('user_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber_user', to='app.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=256)),
                ('items', models.TextField(blank=True)),
                ('order_date', models.CharField(max_length=256)),
                ('order_status', models.CharField(max_length=256)),
                ('order_type', models.CharField(max_length=256, null=True)),
                ('combo_type', models.CharField(max_length=256, null=True)),
                ('bal_combo', models.CharField(max_length=256, null=True)),
                ('order_address', models.CharField(max_length=256, null=True)),
                ('total_amt', models.CharField(max_length=256, null=True)),
                ('single_item', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('user_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_user', to='app.user_data')),
            ],
        ),
    ]
