# Generated by Django 3.2.5 on 2023-09-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meals_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_meals', to='app.meals'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_discount_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
