# Generated by Django 3.2.5 on 2023-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_address_address_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='active',
            field=models.CharField(blank=True, default='Active', max_length=256),
        ),
    ]
