# Generated by Django 3.2.5 on 2023-10-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_balance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='transition_type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
