# Generated by Django 3.2.5 on 2023-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_order_order_address_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date_time',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
